// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEon2RFBhzWabO94f9avhTObRMpA-h5iQ',
    appId: '1:813607639793:android:d46540a82f979d5b852750',
    messagingSenderId: '813607639793',
    projectId: 'nicenotes',
    storageBucket: 'nicenotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIOz8uK17aDRDvOx9reke_LB__hBv--6M',
    appId: '1:813607639793:ios:98ea9ba15c52ac1c852750',
    messagingSenderId: '813607639793',
    projectId: 'nicenotes',
    storageBucket: 'nicenotes.appspot.com',
    iosClientId: '813607639793-3jlpssrg4gqp88r4npvrnltacd0s808r.apps.googleusercontent.com',
    iosBundleId: 'com.nicenotes.www.nicenotes',
  );
}
